spring:
  application:
    name: example-app

fahrschein:
  defaults:
    application-name: stups_outfit-management-api
    consumer-group: stups_outfit-management-api_local
  consumers:
    example: #consumer-id
      read-from: begin
      topics:
      - outfit.outfit-update
#  publishers:
#    - firstPublisher
#    - secondPublisher

logging:
  level:
    com.github.dockerjava: INFO
    org.apache.http: INFO